import { getAllFormFields } from "@/actions/form-builder";
import { AppLayout } from "@/components/layout";
import { AuthProvider } from "@/contexts/auth-context-provider";
import FormBuilderContextProvider from "@/contexts/form-builder-context-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const formFields = await getAllFormFields();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <FormBuilderContextProvider formFields={formFields}>
            <AppLayout>{children}</AppLayout>
          </FormBuilderContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
